nelmio_api_doc:
  documentation:
    info:
      title: API de Torneo de Tenis
      description: |
        Esta API simula torneos de tenis con eliminación directa para jugadores masculinos y femeninos.

        Características principales:
        - Creación y gestión de jugadores con atributos como habilidad, fuerza, velocidad y tiempo de reacción.
        - Simulación de torneos masculinos y femeninos con reglas específicas para cada género.
        - Implementación de lógica de enfrentamientos considerando habilidad y factor suerte.
        - Consulta de resultados de torneos por fecha, género y otros criterios.

        La API está diseñada siguiendo principios de Clean Architecture y buenas prácticas de Programación Orientada a Objetos.
      version: 1.0.0
    openapi: "3.0.0"
    paths:
      /api/player/create:
        post:
          summary: Create a new player
          tags:
            - Player
          requestBody:
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/PlayerInput"
          responses:
            "201":
              description: Player created successfully
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      message:
                        type: string
                        example: "Player created"
            "400":
              description: Bad request
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/ErrorResponse"
      /api/player/{id}:
        get:
          summary: Get player details
          tags:
            - Player
          parameters:
            - name: id
              in: path
              required: true
              schema:
                type: integer
          responses:
            "200":
              description: Player details retrieved successfully
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Player"
            "404":
              description: Player not found
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/ErrorResponse"
      /api/player/list:
        get:
          summary: List players
          tags:
            - Player
          parameters:
            - name: page
              in: query
              schema:
                type: integer
                default: 1
            - name: limit
              in: query
              schema:
                type: integer
                default: 20
            - name: skill
              in: query
              schema:
                type: string
            - name: gender
              in: query
              schema:
                type: string
                enum: [M, F]
          responses:
            "200":
              description: List of players retrieved successfully
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      total:
                        type: integer
                      page:
                        type: integer
                      limit:
                        type: integer
                      players:
                        type: array
                        items:
                          allOf:
                            - $ref: "#/components/schemas/Player"
                            - type: object
                              properties:
                                tournamentsWon:
                                  type: integer
            "404":
              description: No players found
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/ErrorResponse"
            "400":
              description: Bad request
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/ErrorResponse"
      /api/matchup/create:
        post:
          summary: Create a new matchup
          tags:
            - Matchup
          requestBody:
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/MatchupInput"
          responses:
            "201":
              description: Matchup created successfully
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      message:
                        type: string
                        example: "Matchup created successfully"
            "400":
              description: Bad request
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/ErrorResponse"
            "404":
              description: Player or tournament not found
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/ErrorResponse"
      /api/matchup/{id}:
        get:
          summary: Get matchup details
          tags:
            - Matchup
          parameters:
            - name: id
              in: path
              required: true
              schema:
                type: integer
          responses:
            "200":
              description: Matchup details retrieved successfully
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Matchup"
            "404":
              description: Matchup not found
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/ErrorResponse"
      /api/matchup/update/{id}/winner:
        put:
          summary: Update matchup winner
          tags:
            - Matchup
          parameters:
            - name: id
              in: path
              required: true
              schema:
                type: integer
          requestBody:
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    winner_id:
                      type: integer
          responses:
            "200":
              description: Winner updated successfully
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      message:
                        type: string
                        example: "Winner updated successfully"
            "400":
              description: Bad request
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/ErrorResponse"
            "404":
              description: Matchup or winner not found
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/ErrorResponse"
      /api/matchup/list/{tournamentId}:
        get:
          summary: List matchups by tournament
          tags:
            - Matchup
          parameters:
            - name: tournamentId
              in: path
              required: true
              schema:
                type: integer
            - name: finished
              in: query
              schema:
                type: string
                enum: [true, false]
          responses:
            "200":
              description: List of matchups retrieved successfully
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      tournament_id:
                        type: integer
                      matchups:
                        type: array
                        items:
                          $ref: "#/components/schemas/Matchup"
            "400":
              description: Bad request
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/ErrorResponse"
            "404":
              description: No matchups found for this tournament
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/ErrorResponse"
      /api/tournament/create:
        post:
          summary: Create a new tournament
          tags:
            - Tournament
          requestBody:
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/TournamentInput"
          responses:
            "201":
              description: Tournament created successfully
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      message:
                        type: string
                        example: "Tournament created successfully"
                      tournament:
                        $ref: "#/components/schemas/Tournament"
            "400":
              description: Bad request
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/ErrorResponse"
      /api/tournament/{id}:
        get:
          summary: Get tournament details
          tags:
            - Tournament
          parameters:
            - name: id
              in: path
              required: true
              schema:
                type: integer
          responses:
            "200":
              description: Tournament details retrieved successfully
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Tournament"
            "404":
              description: Tournament not found
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/ErrorResponse"
      /api/tournament/simulate:
        post:
          summary: Simulate a tournament
          tags:
            - Tournament
          requestBody:
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    tournament_id:
                      type: integer
          responses:
            "200":
              description: Tournament simulation successful
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      message:
                        type: string
                        example: "Tournament simulation successful"
                      winner:
                        $ref: "#/components/schemas/Player"
            "400":
              description: Bad request
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/ErrorResponse"
            "404":
              description: Tournament not found
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/ErrorResponse"
      /api/tournament/list:
        get:
          summary: List tournaments
          tags:
            - Tournament
          parameters:
            - name: offset
              in: query
              schema:
                type: integer
                default: 0
            - name: limit
              in: query
              schema:
                type: integer
                default: 20
            - name: orderBy
              in: query
              schema:
                type: string
                default: 'createdAt'
            - name: order
              in: query
              schema:
                type: string
                enum: [asc, desc]
                default: 'asc'
          responses:
            "200":
              description: List of tournaments retrieved successfully
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      total:
                        type: integer
                      offset:
                        type: integer
                      limit:
                        type: integer
                      tournaments:
                        type: array
                        items:
                          $ref: "#/components/schemas/Tournament"
            "404":
              description: No tournaments found
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/ErrorResponse"
    components:
      schemas:
        PlayerInput:
          type: object
          required:
            - name
            - skillLevel
            - gender
          properties:
            name:
              type: string
            skillLevel:
              type: integer
              minimum: 0
              maximum: 100
            gender:
              type: string
              enum: [M, F]
            strength:
              type: integer
              minimum: 0
              maximum: 100
            speed:
              type: integer
              minimum: 0
              maximum: 100
            reactionTime:
              type: number
              format: float
              minimum: 0
              maximum: 100
        Player:
          type: object
          properties:
            id:
              type: integer
            name:
              type: string
            skillLevel:
              type: integer
            gender:
              type: string
              enum: [M, F]
            strength:
              type: integer
              nullable: true
            speed:
              type: integer
              nullable: true
            reactionTime:
              type: number
              format: float
              nullable: true
        ErrorResponse:
          type: object
          properties:
            errors:
              type: array
              items:
                type: string
        MatchupInput:
          type: object
          required:
            - player1_id
            - player2_id
            - tournament_id
          properties:
            player1_id:
              type: integer
            player2_id:
              type: integer
            tournament_id:
              type: integer
        Matchup:
          type: object
          properties:
            matchup_id:
              type: integer
            winner_id:
              type: integer
              nullable: true
            player1:
              $ref: "#/components/schemas/Player"
            player2:
              $ref: "#/components/schemas/Player"
        TournamentInput:
          type: object
          required:
            - gender
          properties:
            gender:
              type: string
              enum: [M, F]
        Tournament:
          type: object
          properties:
            id:
              type: integer
            gender:
              type: string
              enum: [M, F]
            winner:
              $ref: "#/components/schemas/Player"
              nullable: true
            created_at:
              type: string
              format: date-time
            finished_at:
              type: string
              format: date-time
              nullable: true